### PR TITLE
Fix for autodiscovery

### PR DESCRIPTION
**Pull request by akelge**
Patch for avahi ros service to allow autodiscovery from RuneAudio
Android app

### CODE REVIEW

**Comment by rern** [comment]
The app is just a wrapper of a browser which I think we're better off with Chrome "**Home Screen Shortcut**" / Safari "**Add to Home Screen**" instead.
By the way, Avahi name should be the same as hostname. That's the `%h` variable which is `rAudio` as default.

**Comment by akelge** [comment]
I know, but it is useful because of the auto discovery, for “normal” users (i.e. my wife or my daughter or any non IT ;) )
What I have found (but I can be wrong) is that if it misses the `[macaddress]` part the server is not discovered.
On the other side it seems there is no check for the validity of the macaddress, so `00:00:00:00:00:00` (although ugly) works.

**Comment by akelge** [comment]
I see you closed the pull request. I wonder why. I know you don't like to use autodiscovery but it is there and not working.
Why not just make it work? Then if someone does not want to use it, they will not ;)
If you think this feature should be fixed in a better way, like using the proper MAC address, just let me know and I can work on it.

**Comment by rern** [comment]
It's by/for **RuneAudio**.
**rAudio** is another player.
Sell me the pros of the app.

**Comment by akelge** [comment]
1. Branding: so your version is called rAudio? I can try to see if the app works with rAudio. I agree with you it would be better to rename completely the software, to solve the ambiguity.
2. No particular pros, apart for auto discovery. You launch the app, it finds the rAudio instance(s) and you are done, no need to know URLs. Other than that, it goes full screen on my phone, no top bar ;)

A.

**Pull request closed without merging**
